[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8", "wheel", "scikit_build_core"]
build-backend = "scikit_build_core.build"

[project]
name = "histogrammer"
description = "odin-control adapter project for Hexitec Histogrammer"
dynamic = ["version"]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: >=3.10",
]
dependencies = [
    "pybind11",
    "odin-control @ git+https://github.com/odin-detector/odin-control",
]

readme = "README.md"

[[project.authors]]
email = "ashley.neaves@stfc.ac.uk"
name = "Ashley Neaves"

[project.optional-dependencies]
odin_control = [
    "odin-control @ git+https://github.com/odin-detector/odin-control@1.6.0#egg=odin-control"
]
